= Adventures in the Land of Knex.js
:hp-tags: javascript, knex, databases

The latest addition to my Javascript toolbet is *Knex.js*. The query builder that powers other libraries, such as link:http://bookshelfjs.org/[bookshelf.js]. As they say it's a _batteries included_ SQL query builder, amazingly fast and even more easy and *fun* to use, it's the definitive tool to learn. If you are not still convinced, it supports the traditional (aka callback-hell) and *promise* interfaces.

Enough with talking, this library supports *Postgres, MySQL, MariaDB, SQLite3, and Oracle*.

_This tutorial is going to cover only the postgres part, but knex can handle the others with the same interface, besides SQLite3, which requires setting the path, but it's extremely simple_

== Getting to work!
Installing it is simple, inside your npm project just run these commands:

[source,bash]
----
$ npm install knex --save #for the project
$ npm install knex -g #for the tools I'm going to explain later
$ npm install pg --save #because we need the driver!
----

Once the dependencies are installed, you can just mess around, with the queries:

[source,js]
----
var knex = require('knex')({
  client: 'mysql',
  connection: {
    host     : '127.0.0.1',
    user     : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  }
});
----

